### ISSUE TITLE
Problem with Websockets

### ISSUE THREAD

**Issue by rommsen** [rommsen/Fable.Reaction.Playground#1]
@dbrattli I have problems with the websocket operator
1. How do I open a websocket that is only listening but not pushing anything? Here: https://github.com/rommsen/Fable.Reaction.Playground/blob/4c47ba7b35e86880e5c974e1dacd1df3ac7abcc5/src/Client/Info.fs#L117 I make an artifical observable out of the msgs stream to be able to connect with the ws. the filter will actually never match and the map is ugly. Is there any better way to achive it. If I use `Seq.empty |> ofSeq` the websocket is closed immediately

2. How do I create my observables when I want to have to different streams based on one websocket? (different Msg pushed to update)? Do I have to use flatmap? The way I do it here: https://github.com/rommsen/Fable.Reaction.Playground/blob/4c47ba7b35e86880e5c974e1dacd1df3ac7abcc5/src/Client/Info.fs#L125 two websocket connections are created because I create to different streams.

**Comment by dbrattli** [comment]
1) Compose it with an observable that never produces a value. I never thought I would need it but we do. I'll add it soon to Reaction.

```fs
let inline never<'a> () : IAsyncObservable<'a> =
    Create.ofAsyncWorker (fun obv _ -> async {
        ()
    })
```

Then something like:

```fs
let ws =
     never<Shared.Msg> () |> server
```

2) This is where we need new operators for Reaction: `share` aka `publish/refCount`. I'm on the task. For more info see http://reactivex.io/documentation/operators/refcount.html, https://blog.angularindepth.com/rxjs-understanding-the-publish-and-share-operators-16ea2f446635

**Comment by dbrattli** [comment]
Another way of doing 2) is that we make it possible to reference another named observables that have/are been returned. Something like `ofStream(key/name)`, and then hide all the `publish/refCount` behind the scenes.

**Comment by rommsen** [comment]
Cool thanks. Will read the articles you linked to me

**Comment by dbrattli** [comment]
Might be fixed by pull request. Please have a look.
